const OAUTH_GOOGLE_REQUEST = 'OAUTH_GOOGLE_REQUEST'
const OAUTH_GOOGLE_SUCCESS = 'OAUTH_GOOGLE_SUCCESS'
const OAUTH_GOOGLE_FAILED = 'OAUTH_GOOGLE_FAILED'

const OAUTH_FACEBOOK_REQUEST = 'OAUTH_FACEBOOK_REQUEST'
const OAUTH_FACEBOOK_SUCCESS = 'OAUTH_FACEBOOK_SUCCESS'
const OAUTH_FACEBOOK_FAILED = 'OAUTH_FACEBOOK_FAILED'

const LOGIN_REQUEST = 'LOGIN_REQUEST'
const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
const LOGIN_FAILED = 'LOGIN_FAILED'

const REGISTER_REQUEST = 'REGISTER_REQUEST'
const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
const REGISTER_FAILED = 'REGISTER_FAILED'

const GET_CURRENT_SUCCESS = 'GET_CURRENT_SUCCESS'
const GET_CURRENT_FAILED = 'GET_CURRENT_FAILED'

const FORGOT_PASSWORD_REQUEST = 'FORGOT_PASSWORD_REQUEST'
const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS'
const FORGOT_PASSWORD_FAILED = 'FORGOT_PASSWORD_FAILED'

const RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST'
const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS'
const RESET_PASSWORD_FAILED = 'RESET_PASSWORD_FAILED'

const SET_BASIC_INFO_REQUEST = 'SET_BASIC_INFO_REQUEST'
const SET_BASIC_INFO_SUCCESS = 'SET_BASIC_INFO_SUCCESS'
const SET_BASIC_INFO_FAILED = 'SET_BASIC_INFO_FAILED'

const ONBOARDING_COMPLETE_REQUEST = 'ONBOARDING_COMPLETE_REQUEST'
const ONBOARDING_COMPLETE_SUCCESS = 'ONBOARDING_COMPLETE_SUCCESS'
const ONBOARDING_COMPLETE_FAILED = 'ONBOARDING_COMPLETE_FAILED'

const SET_BANK_ACCOUNT_REQUEST = 'SET_BANK_ACCOUNT_REQUEST'
const SET_BANK_ACCOUNT_SUCCESS = 'SET_BANK_ACCOUNT_SUCESS'
const SET_BANK_ACCOUNT_FAILED = 'SET_BANK_ACCOUNT_FAILED'

const CHANGE_PASSWORD_REQUEST = 'CHANGE_PASSWORD_REQUEST'
const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCESS'
const CHANGE_PASSWORD_FAILED = 'CHANGE_PASSWORD_FAILED'

const UPDATE_PROFILE_REQUEST = 'UPDATE_PROFILE_REQUEST'
const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS'
const UPDATE_PROFILE_FAILED = 'UPDATE_PROFILE_FAILED '

const UPDATE_USERNAME_REQUEST = 'UPDATE_USERNAME_REQUEST'
const UPDATE_USERNAME_SUCCESS = 'UPDATE_USERNAME_SUCCESS'
const UPDATE_USERNAME_FAILED = 'UPDATE_USERNAME_FAILED '

const UPDATE_ID_CARD_REQUEST = 'UPDATE_ID_CARD_REQUEST'
const UPDATE_ID_CARD_SUCCESS = 'UPDATE_ID_CARD_SUCCESS'
const UPDATE_ID_CARD_FAILED = 'UPDATE_ID_CARD_FAILED '

const VALIDATE_SIGNATURE_RESET_PASSWORD_REQUEST =
  'VALIDATE_SIGNATURE_RESET_PASSWORD_REQUEST'
const VALIDATE_SIGNATURE_RESET_PASSWORD_SUCCESS =
  'VALIDATE_SIGNATURE_RESET_PASSWORD_SUCCESS'
const VALIDATE_SIGNATURE_RESET_PASSWORD_FAILED =
  'VALIDATE_SIGNATURE_RESET_PASSWORD_FAILED '

const VALIDATE_SIGNATURE_EMAIL_REQUEST = 'VALIDATE_SIGNATURE_EMAIL_REQUEST'
const VALIDATE_SIGNATURE_EMAIL_SUCCESS = 'VALIDATE_SIGNATURE_EMAIL_SUCCESS'
const VALIDATE_SIGNATURE_EMAIL_FAILED = 'VALIDATE_SIGNATURE_EMAIL_FAILED '

const SET_USER_SERVICE_REQUEST = 'SET_USER_SERVICE_REQUEST'
const SET_USER_SERVICE_SUCCESS = 'SET_USER_SERVICE_SUCCESS'
const SET_USER_SERVICE_FAILED = 'SET_USER_SERVICE_FAILED'

const VERIFY_EMAIL_REQUEST = 'VERIFY_EMAIL_REQUEST'
const VERIFY_EMAIL_SUCCESS = 'VERIFY_EMAIL_SUCCESS'
const VERIFY_EMAIL_FAILED = 'VERIFY_EMAIL_FAILED'

const EDIT_EMAIL_REQUEST = 'EDIT_EMAIL_REQUEST'
const EDIT_EMAIL_SUCCESS = 'EDIT_EMAIL_SUCCESS'
const EDIT_EMAIL_FAILED = 'EDIT_EMAIL_FAILED'

const PLATFORM_CONNECT_REQUEST = 'PLATFORM_CONNECT_REQUEST'
const PLATFORM_CONNECT_SUCCESS = 'PLATFORM_CONNECT_SUCCESS'
const PLATFORM_CONNECT_FAILED = 'PLATFORM_CONNECT_FAILED'

const PLATFORM_POST_CONNECT_REQUEST = 'PLATFORM_POST_CONNECT_REQUEST'
const PLATFORM_POST_CONNECT_SUCCESS = 'PLATFORM_POST_CONNECT_SUCCESS'
const PLATFORM_POST_CONNECT_FAILED = 'PLATFORM_POST_CONNECT_FAILED'

const UAP_DISCONNECT_REQUEST = 'UAP_DISCONNECT_REQUEST'
const UAP_DISCONNECT_SUCCESS = 'UAP_DISCONNECT_SUCCESS'
const UAP_DISCONNECT_FAILED = 'UAP_DISCONNECT_FAILED'

const CHECK_USER_AVAILABILITY_REQUEST = 'CHECK_USER_AVAILABILITY_REQUEST'
const CHECK_USER_AVAILABILITY_SUCCESS = 'CHECK_USER_AVAILABILITY_SUCCESS'
const CHECK_USER_AVAILABILITY_FAILED = 'CHECK_USER_AVAILABILITY_FAILED'

const GET_USER_FROM_AUTH_ACCOUNT_AND_PROVIDER_REQUEST =
  'GET_USER_FROM_AUTH_ACCOUNT_AND_PROVIDER_REQUEST'
const GET_USER_FROM_AUTH_ACCOUNT_AND_PROVIDER_SUCCESS =
  'GET_USER_FROM_AUTH_ACCOUNT_AND_PROVIDER_SUCCESS'
const GET_USER_FROM_AUTH_ACCOUNT_AND_PROVIDER_FAILED =
  'GET_USER_FROM_AUTH_ACCOUNT_AND_PROVIDER_FAILED'

const UPDATE_USER_CONFIGURATION_REQUEST = 'UPDATE_USER_CONFIGURATION_REQUEST'
const UPDATE_USER_CONFIGURATION_SUCCESS = 'UPDATE_USER_CONFIGURATION_SUCCESS'
const UPDATE_USER_CONFIGURATION_FAILED = 'UPDATE_USER_CONFIGURATION_FAILED'

const GET_USER_EMAIL_BY_ID_REQUEST = 'GET_USER_BY_ID_REQUEST'
const GET_USER_EMAIL_BY_ID_SUCCESS = 'GET_USER_BY_ID_SUCCESS'
const GET_USER_EMAIL_BY_ID_FAILED = 'GET_USER_BY_ID_FAILED'

const LOGOUT = 'LOGOUT'

const SET_SOCKET_STATUS = 'SET_SOCKET_STATUS'
const SET_VISIBILITY_SNACKBAR_ONBOARDING = 'SET_VISIBILITY_SNACKBAR_ONBOARDING'

export default {
  LOGIN_REQUEST,
  LOGIN_SUCCESS,
  LOGIN_FAILED,

  REGISTER_REQUEST,
  REGISTER_SUCCESS,
  REGISTER_FAILED,

  FORGOT_PASSWORD_REQUEST,
  FORGOT_PASSWORD_SUCCESS,
  FORGOT_PASSWORD_FAILED,

  RESET_PASSWORD_REQUEST,
  RESET_PASSWORD_SUCCESS,
  RESET_PASSWORD_FAILED,

  SET_BASIC_INFO_REQUEST,
  SET_BASIC_INFO_SUCCESS,
  SET_BASIC_INFO_FAILED,

  ONBOARDING_COMPLETE_REQUEST,
  ONBOARDING_COMPLETE_SUCCESS,
  ONBOARDING_COMPLETE_FAILED,

  GET_CURRENT_SUCCESS,
  GET_CURRENT_FAILED,

  SET_BANK_ACCOUNT_REQUEST,
  SET_BANK_ACCOUNT_SUCCESS,
  SET_BANK_ACCOUNT_FAILED,

  CHANGE_PASSWORD_REQUEST,
  CHANGE_PASSWORD_SUCCESS,
  CHANGE_PASSWORD_FAILED,

  UPDATE_PROFILE_REQUEST,
  UPDATE_PROFILE_SUCCESS,
  UPDATE_PROFILE_FAILED,

  UPDATE_USERNAME_REQUEST,
  UPDATE_USERNAME_SUCCESS,
  UPDATE_USERNAME_FAILED,

  UPDATE_ID_CARD_REQUEST,
  UPDATE_ID_CARD_SUCCESS,
  UPDATE_ID_CARD_FAILED,

  VALIDATE_SIGNATURE_RESET_PASSWORD_REQUEST,
  VALIDATE_SIGNATURE_RESET_PASSWORD_SUCCESS,
  VALIDATE_SIGNATURE_RESET_PASSWORD_FAILED,

  VALIDATE_SIGNATURE_EMAIL_REQUEST,
  VALIDATE_SIGNATURE_EMAIL_SUCCESS,
  VALIDATE_SIGNATURE_EMAIL_FAILED,

  SET_USER_SERVICE_REQUEST,
  SET_USER_SERVICE_SUCCESS,
  SET_USER_SERVICE_FAILED,

  VERIFY_EMAIL_REQUEST,
  VERIFY_EMAIL_SUCCESS,
  VERIFY_EMAIL_FAILED,

  EDIT_EMAIL_REQUEST,
  EDIT_EMAIL_SUCCESS,
  EDIT_EMAIL_FAILED,

  PLATFORM_CONNECT_REQUEST,
  PLATFORM_CONNECT_SUCCESS,
  PLATFORM_CONNECT_FAILED,

  PLATFORM_POST_CONNECT_REQUEST,
  PLATFORM_POST_CONNECT_SUCCESS,
  PLATFORM_POST_CONNECT_FAILED,

  UAP_DISCONNECT_REQUEST,
  UAP_DISCONNECT_SUCCESS,
  UAP_DISCONNECT_FAILED,

  CHECK_USER_AVAILABILITY_REQUEST,
  CHECK_USER_AVAILABILITY_SUCCESS,
  CHECK_USER_AVAILABILITY_FAILED,

  GET_USER_FROM_AUTH_ACCOUNT_AND_PROVIDER_REQUEST,
  GET_USER_FROM_AUTH_ACCOUNT_AND_PROVIDER_SUCCESS,
  GET_USER_FROM_AUTH_ACCOUNT_AND_PROVIDER_FAILED,

  UPDATE_USER_CONFIGURATION_REQUEST,
  UPDATE_USER_CONFIGURATION_SUCCESS,
  UPDATE_USER_CONFIGURATION_FAILED,

  GET_USER_EMAIL_BY_ID_REQUEST,
  GET_USER_EMAIL_BY_ID_SUCCESS,
  GET_USER_EMAIL_BY_ID_FAILED,

  LOGOUT,
  SET_SOCKET_STATUS,
  SET_VISIBILITY_SNACKBAR_ONBOARDING,

  OAUTH_GOOGLE_REQUEST,
  OAUTH_GOOGLE_SUCCESS,
  OAUTH_GOOGLE_FAILED,

  OAUTH_FACEBOOK_REQUEST,
  OAUTH_FACEBOOK_SUCCESS,
  OAUTH_FACEBOOK_FAILED
}
